name = "NonCommutativeProducts"
uuid = "a9a0a982-c603-4485-bf80-6b61b825abb4"
authors = ["Viktor Svensson <13223396+cvsvensson@users.noreply.github.com> and contributors"]
version = "0.3.5"

[deps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
BangBang = "0.4"
LinearAlgebra = "1"
Test = "1"
TestItems = "1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
